[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "libxml2", "libxslt", "gcc"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "gunicorn app:app --bind 0.0.0.0:$PORT"
